name: CI

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: g++ main.cpp

    - name: Test
      run: ./a.out

    - name: Docker build
      run: docker build --tag too-simple-hol .
