name: CI

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: g++ main.cpp

    - name: Test
      run: ./a.out

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Docker build
      run: docker build -t too-simple-hol .

    - name: Docker push
      run: |
        docker tag too-simple-hol ghcr.io/wnaldj1589tw/github_action_test/too-simple-hol:latest
        docker push ghcr.io/wnaldj1589tw/github_action_test/too-simple-hol:latest
