name: CI

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Get the branch
      id: get-branch
      run: |
          if [[ ${GITHUB_REF#refs/heads/} == 'master' ]]
          then
              _branch='master'
          else
              if [[ ${GITHUB_REF#refs/heads/} == 'develop' ]]
              then
                  _branch='develop'
              else
                  _branch=$(echo ${GITHUB_REF#refs/heads/} | cut -d'/' -f2)
              fi
          fi
          echo ::set-output name=branch::${_branch,,}

    - name: Print branch name
      run: echo ${{ steps.get-branch.outputs.branch }}
