name: CI

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: g++ main.cpp

    - name: Test
      run: ./a.out

    - name: Docker build
      run: docker build -t too-simple-hol .

    - name: Docker push
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
        docker tag too-simple-hol ghcr.io/wnaldj1589tw/github_action_test/too-simple-hol:latest
        docker push ghcr.io/wnaldj1589tw/github_action_test/too-simple-hol:latest
