name: CI

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: g++ main.cpp

    - name: Test
      run: ./a.out

    - name: Docker build
      run: docker build --tag ghcr.io/wnaldj1589TW/github_action_test/too-simple-hol:latest .

    - name: Docker push
      run: docker push ghcr.io/wnaldj1589TW/github_action_test/too-simple-hol:latest .
