name: CI

on: [push]

strategy:
  matrix:
    compiler: [g++]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        CC: ${{ matrix.compiler }}
      run: CC main.cpp

    - name: Test
      env:
        CC: ${{ matrix.compiler }}
      run: ./a.out

